-- 在 Supabase SQL Editor 执行

create table if not exists public.space_items (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  description text,
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.space_items enable row level security;

-- 公开读写策略（演示环境）
drop policy if exists "space_items_select_all" on public.space_items;
create policy "space_items_select_all"
on public.space_items for select
to anon
using (true);

drop policy if exists "space_items_insert_all" on public.space_items;
create policy "space_items_insert_all"
on public.space_items for insert
to anon
with check (true);

drop policy if exists "space_items_update_all" on public.space_items;
create policy "space_items_update_all"
on public.space_items for update
to anon
using (true)
with check (true);

drop policy if exists "space_items_delete_all" on public.space_items;
create policy "space_items_delete_all"
on public.space_items for delete
to anon
using (true);

-- 建议在 Storage 新建公开 bucket: space-images
-- 并增加以下策略（Storage Policies 页面添加）
-- 1) Select: bucket_id = 'space-images'
-- 2) Insert: bucket_id = 'space-images'
-- 3) Update/Delete: bucket_id = 'space-images'
