-- Run this in Supabase SQL Editor.
-- It resets the public read/write policies used by the GitHub Pages app.

create table if not exists public.space_items (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  description text,
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.space_items enable row level security;

drop policy if exists "space_items_select_all" on public.space_items;
create policy "space_items_select_all"
on public.space_items for select
to anon
using (true);

drop policy if exists "space_items_insert_all" on public.space_items;
create policy "space_items_insert_all"
on public.space_items for insert
to anon
with check (true);

drop policy if exists "space_items_update_all" on public.space_items;
create policy "space_items_update_all"
on public.space_items for update
to anon
using (true)
with check (true);

drop policy if exists "space_items_delete_all" on public.space_items;
create policy "space_items_delete_all"
on public.space_items for delete
to anon
using (true);

insert into storage.buckets (id, name, public)
values ('space-images', 'space-images', true)
on conflict (id) do update set public = true;

drop policy if exists "space_images_select_all" on storage.objects;
create policy "space_images_select_all"
on storage.objects for select
to anon
using (bucket_id = 'space-images');

drop policy if exists "space_images_insert_all" on storage.objects;
create policy "space_images_insert_all"
on storage.objects for insert
to anon
with check (bucket_id = 'space-images');

drop policy if exists "space_images_update_all" on storage.objects;
create policy "space_images_update_all"
on storage.objects for update
to anon
using (bucket_id = 'space-images')
with check (bucket_id = 'space-images');

drop policy if exists "space_images_delete_all" on storage.objects;
create policy "space_images_delete_all"
on storage.objects for delete
to anon
using (bucket_id = 'space-images');
